### ISSUE TITLE
[PE-D][Tester E] Commands stated in the Command summary section are not updated

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W13-4/tp#107]
In he `Command summary` section in the user guide, the unassign task, clear task, and exit command are not added here.

![image.png](https://raw.githubusercontent.com/zengzihui/ped/main/files/35b9e3c4-f73a-4e43-bf49-95b5429e437e.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: zengzihui/ped#9

**Comment by Yskie** [comment]
Fixed in #139.
