### ISSUE TITLE
[PE-D][Tester C] Difficulty in seeing Priority of Task in GUI

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W13-4/tp#74]
It is quite difficult for users to see the Priority level of each Task due to the striking green colour of the block with the white colour of the font

![Screenshot 2024-04-05 at 4.11.24 PM.png](https://raw.githubusercontent.com/soons1/ped/main/files/297f3d80-c241-43b5-adf2-3c31f858d20d.png)

As seen in the screenshot above, it takes some squinting to see the 'LOW' in the GUI

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: soons1/ped#2

**Comment by chin-herng** [comment]
Addressed as a feature flaw in the 'Planned Enhancements' DG appendix.
