### ISSUE TITLE
[PE-D][Tester D] Can't have same name in the addressbook

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W13-4/tp#78]
Unable to add people with the same name even with different phone numbers, emails and address. Would it be possible to look into that as some people might have the same name?

![image.png](https://raw.githubusercontent.com/xuelinglow/ped/main/files/e6136f72-49cd-494c-8af3-2c40525e4814.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: xuelinglow/ped#3

**Comment by chin-herng** [comment]
Addressed as a feature flaw in the 'Planned Enhancements' DG appendix.
