### ISSUE TITLE
[PE-D][Tester D] Description cuts off if too long

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W13-4/tp#80]
Steps to reproduce:

    1.  addtask n/Task 1 d/Do homeworkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk p/HIGH

![image.png](https://raw.githubusercontent.com/xuelinglow/ped/main/files/ded84e69-033c-4b4f-9e61-d7e95d09af43.png)
Description cuts off in the layout if it is too long.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: xuelinglow/ped#4

**Comment by Yskie** [comment]
Done, fixed in #110.
