### ISSUE TITLE
[PE-D][Tester A] Duplicate Persons

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W13-4/tp#91]
A user should be able to input 2 contacts of same name but different address, email and phone number, which should be a plausible scenario. The app however assumes the person's name solely to be a unique identifier. Perhaps you can include a combination of the fields for a unique person contact.

![Screenshot 2024-04-05 at 16.35.45.png](https://raw.githubusercontent.com/Jawad280/ped/main/files/c0050a72-c010-4ecb-a810-af0f89cf592b.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Jawad280/ped#4

**Comment by chin-herng** [comment]
Addressed as a feature flaw in the 'Planned Enhancements' DG appendix.
